### ISSUE TITLE
Version builds

### ISSUE THREAD

**Issue by SGTGunner** [ESX-Org/esx_menu_list#2]
More a question than a bug fix.

What is the release policy around the promotion of builds? I notice that a change in master was made 10 days ago. Which bumped it 1.0.2 in comparison to the releases area that has only a build of 1.0.1, when does it go into an official release?

Is there any automation around testing and then building into an official release?
Or should I take for granted that anything in master is good to go?

Thanks in advance.

**Comment by ElPumpo** [comment]
we never push incomplete code to master branch. Every commit does not bump version, duh.
